-- MySQL Script generated by MySQL Workbench
-- Sat May 14 12:13:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema les_troubles_dys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema les_troubles_dys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `les_troubles_dys` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `les_troubles_dys` ;

-- -----------------------------------------------------
-- Table `les_troubles_dys`.`mdf58_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `les_troubles_dys`.`mdf58_role` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `les_troubles_dys`.`mdf58_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `les_troubles_dys`.`mdf58_user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `validation_key` VARCHAR(10) NOT NULL,
  `valid` TINYINT(1) NOT NULL DEFAULT '0',
  `email` VARCHAR(150) NOT NULL,
  `firstname` VARCHAR(150) NOT NULL,
  `lastname` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `mdf58_role_fk` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_mdf58_user_mdf58_role1_idx` (`mdf58_role_fk` ASC),
  CONSTRAINT `fk_mdf58_user_mdf58_role1`
    FOREIGN KEY (`mdf58_role_fk`)
    REFERENCES `les_troubles_dys`.`mdf58_role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `les_troubles_dys`.`mdf58_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `les_troubles_dys`.`mdf58_article` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `summary` TEXT NOT NULL,
  `image` VARCHAR(155) NOT NULL,
  `mdf58_user_fk` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mdf58_article_mdf58_user_idx` (`mdf58_user_fk` ASC),
  CONSTRAINT `fk_mdf58_article_mdf58_user`
    FOREIGN KEY (`mdf58_user_fk`)
    REFERENCES `les_troubles_dys`.`mdf58_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 93
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `les_troubles_dys`.`mdf58_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `les_troubles_dys`.`mdf58_comments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `mdf58_user_fk` INT(10) UNSIGNED NOT NULL,
  `mdf58_article_fk` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mdf58_comments_mdf58_user1_idx` (`mdf58_user_fk` ASC),
  INDEX `fk_mdf58_comments_mdf58_article1_idx` (`mdf58_article_fk` ASC),
  CONSTRAINT `fk_mdf58_comments_mdf58_article1`
    FOREIGN KEY (`mdf58_article_fk`)
    REFERENCES `les_troubles_dys`.`mdf58_article` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mdf58_comments_mdf58_user1`
    FOREIGN KEY (`mdf58_user_fk`)
    REFERENCES `les_troubles_dys`.`mdf58_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
